#!/usr/bin/env python3
"""Generate local split rule files for zlbzhf/Surge.

The main profile follows SukkaW's global ordering principle:
DOMAIN-SET/domainset -> non_ip -> ip -> FINAL.

blackmatrix7 service lists are useful for app-level policies, but some lists are
mixed Surge lists containing both domain-like rules and IP-CIDR rules. This
script fetches the upstream lists declared in sources/rules.yaml, splits them
into local non_ip/ip files, and rewrites the main config to reference those
local generated files instead of the mixed upstream URLs.
"""
from __future__ import annotations

import argparse
import difflib
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
SOURCES_FILE = ROOT / "sources" / "rules.yaml"
GENERATED_DIR = ROOT / "rules" / "blackmatrix7"
CONFIG_FILES = [ROOT / "Surge.conf", ROOT / "Surge-SukkaW-Blackmatrix7.conf"]

IP_RULE_PREFIXES = {
    "IP-CIDR",
    "IP-CIDR6",
    "IP-ASN",
    "GEOIP",
    "IP6-CIDR",
}

NON_IP_BLOCK_START_PREFIX = "# > blackmatrix7 单 App 补充规则"
IP_BLOCK_START_PREFIX = "# > blackmatrix7 单 App IP 规则"
APPLE_MARKER = "# > Apple"
TELEGRAM_IP_MARKER = "# > Telegram IP CIDR / ASN"


@dataclass(frozen=True)
class AppRule:
    name: str
    policy: str
    path: str


@dataclass(frozen=True)
class Sources:
    local_raw_base: str
    blackmatrix7_base_url: str
    apps: list[AppRule]


def _value_after_colon(line: str) -> str:
    return line.split(":", 1)[1].strip().strip('"').strip("'")


def load_sources(path: Path = SOURCES_FILE) -> Sources:
    """Parse the small YAML subset used by sources/rules.yaml.

    The repo intentionally avoids a PyYAML dependency so generation works in a
    clean GitHub Actions Python environment.
    """
    local_raw_base = ""
    blackmatrix7_base_url = ""
    apps: list[AppRule] = []
    current: dict[str, str] | None = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        if stripped.startswith("local_raw_base:"):
            local_raw_base = _value_after_colon(stripped)
            continue
        if stripped.startswith("base_url:"):
            blackmatrix7_base_url = _value_after_colon(stripped)
            continue

        if stripped.startswith("- name:"):
            if current:
                apps.append(AppRule(**current))
            current = {"name": _value_after_colon(stripped)}
            continue
        if current is not None and stripped.startswith("policy:"):
            current["policy"] = _value_after_colon(stripped)
            continue
        if current is not None and stripped.startswith("path:"):
            current["path"] = _value_after_colon(stripped)
            continue

    if current:
        apps.append(AppRule(**current))

    missing = []
    if not local_raw_base:
        missing.append("repository.local_raw_base")
    if not blackmatrix7_base_url:
        missing.append("blackmatrix7.base_url")
    for idx, app in enumerate(apps, start=1):
        for field in ("name", "policy", "path"):
            if not getattr(app, field):
                missing.append(f"blackmatrix7.apps[{idx}].{field}")
    if missing:
        raise SystemExit(f"Invalid sources/rules.yaml, missing: {', '.join(missing)}")
    return Sources(
        local_raw_base=local_raw_base.rstrip("/"),
        blackmatrix7_base_url=blackmatrix7_base_url.rstrip("/"),
        apps=apps,
    )


def fetch_text(url: str, timeout: int = 30) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "zlbzhf/Surge generator"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read().decode("utf-8", errors="replace")


def normalize_rule_lines(text: str) -> list[str]:
    lines: list[str] = []
    seen: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Keep upstream order while removing accidental duplicates.
        if line not in seen:
            seen.add(line)
            lines.append(line)
    return lines


def is_ip_rule(line: str) -> bool:
    token = line.split(",", 1)[0].strip().upper()
    return token in IP_RULE_PREFIXES


def render_generated_rule_file(app: AppRule, source_url: str, kind: str, lines: Iterable[str]) -> str:
    body = list(lines)
    header = [
        f"# NAME: {app.name}.{kind}",
        "# AUTHOR: generated by zlbzhf/Surge scripts/generate.py",
        f"# SOURCE: {source_url}",
        "# NOTE: Generated file. Do not edit manually; edit sources/rules.yaml or generator logic instead.",
        f"# KIND: {kind}",
        f"# TOTAL: {len(body)}",
        "",
    ]
    return "\n".join(header + body) + "\n"


def update_file(path: Path, content: str, check: bool) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return False
    if check:
        print(f"::error file={path.relative_to(ROOT)}::generated content is out of date", file=sys.stderr)
        if old is not None:
            diff = difflib.unified_diff(
                old.splitlines(),
                content.splitlines(),
                fromfile=str(path.relative_to(ROOT)),
                tofile=str(path.relative_to(ROOT)) + " (generated)",
                lineterm="",
            )
            for line in list(diff)[:120]:
                print(line, file=sys.stderr)
        else:
            print("missing generated file", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def remove_file(path: Path, check: bool) -> bool:
    if not path.exists():
        return False
    if check:
        print(f"::error file={path.relative_to(ROOT)}::stale generated file should be removed", file=sys.stderr)
        return True
    path.unlink()
    print(f"removed {path.relative_to(ROOT)}")
    return True


def replace_between_markers(text: str, start_prefix: str, end_marker: str, replacement: str) -> str:
    lines = text.splitlines()
    start = next((i for i, line in enumerate(lines) if line.startswith(start_prefix)), None)

    if start is None:
        # Insert before the first matching end marker if this block has never existed.
        end = next((i for i, line in enumerate(lines) if line.startswith(end_marker)), None)
        if end is None:
            raise SystemExit(f"Could not find marker: {end_marker}")
        return "\n".join(lines[:end] + replacement.splitlines() + [""] + lines[end:]) + "\n"

    # Replace until the first end marker *after* the block start. The same marker
    # text can appear earlier in the proxy-group comments.
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith(end_marker)), None)
    if end is None:
        raise SystemExit(f"Could not find marker after {start_prefix}: {end_marker}")
    return "\n".join(lines[:start] + replacement.splitlines() + [""] + lines[end:]) + "\n"


def render_non_ip_block(sources: Sources, generated: dict[str, dict[str, int]]) -> str:
    lines = [
        "# > blackmatrix7 单 App 补充规则（由 scripts/generate.py 拆分生成）",
        "# > 本段只引用本仓库生成的 non_ip 列表；上游 mixed list 中的 IP-CIDR 会进入后面的 IP 区域。",
        "# > 独立 App 策略组只用于功能/解锁/IP 风控确有差异的服务，不为了细分而细分。",
    ]
    for app in sources.apps:
        if generated[app.name]["non_ip"] > 0:
            url = f"{sources.local_raw_base}/rules/blackmatrix7/{app.name}.non_ip.list"
            lines.append(f"RULE-SET,{url},{app.policy}")
    return "\n".join(lines)


def render_ip_block(sources: Sources, generated: dict[str, dict[str, int]]) -> str:
    lines = [
        "# > blackmatrix7 单 App IP 规则（由 scripts/generate.py 拆分生成）",
        "# > 与上方 non_ip 列表配套，保持全局 domainset -> non_ip -> ip 顺序。",
    ]
    active = 0
    for app in sources.apps:
        if generated[app.name]["ip"] > 0:
            url = f"{sources.local_raw_base}/rules/blackmatrix7/{app.name}.ip.list"
            lines.append(f"RULE-SET,{url},{app.policy}")
            active += 1
    if active == 0:
        lines.append("# > 当前没有 blackmatrix7 单 App IP 规则。")
    return "\n".join(lines)


def update_config(path: Path, sources: Sources, generated: dict[str, dict[str, int]], check: bool) -> bool:
    text = path.read_text(encoding="utf-8")
    text = replace_between_markers(text, NON_IP_BLOCK_START_PREFIX, APPLE_MARKER, render_non_ip_block(sources, generated))
    text = replace_between_markers(text, IP_BLOCK_START_PREFIX, TELEGRAM_IP_MARKER, render_ip_block(sources, generated))
    text = text.replace(
        "# > 说明：以 SukkaW 规则为主干，blackmatrix7 补充关键 App 单独策略；广告/MITM 高风险项默认注释。",
        "# > 说明：以 SukkaW 规则为主干，blackmatrix7 补充关键 App 单独策略；blackmatrix7 mixed list 由生成器拆分为 non_ip/ip；广告/MITM 高风险项默认注释。",
    )
    return update_file(path, text, check)


def generate(check: bool = False) -> int:
    sources = load_sources()
    changed = False
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    generated: dict[str, dict[str, int]] = {}
    expected_files: set[Path] = set()

    for app in sources.apps:
        source_url = f"{sources.blackmatrix7_base_url}/{app.path}"
        upstream = fetch_text(source_url)
        rules = normalize_rule_lines(upstream)
        ip_lines = [line for line in rules if is_ip_rule(line)]
        non_ip_lines = [line for line in rules if not is_ip_rule(line)]
        generated[app.name] = {"non_ip": len(non_ip_lines), "ip": len(ip_lines)}

        non_ip_path = GENERATED_DIR / f"{app.name}.non_ip.list"
        expected_files.add(non_ip_path)
        changed |= update_file(non_ip_path, render_generated_rule_file(app, source_url, "non_ip", non_ip_lines), check)

        ip_path = GENERATED_DIR / f"{app.name}.ip.list"
        if ip_lines:
            expected_files.add(ip_path)
            changed |= update_file(ip_path, render_generated_rule_file(app, source_url, "ip", ip_lines), check)
        else:
            changed |= remove_file(ip_path, check)

        print(f"{app.name}: non_ip={len(non_ip_lines)} ip={len(ip_lines)}")

    for stale in GENERATED_DIR.glob("*.list"):
        if stale not in expected_files:
            changed |= remove_file(stale, check)

    for config in CONFIG_FILES:
        changed |= update_config(config, sources, generated, check)

    if check and changed:
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files/configs are up to date without writing")
    args = parser.parse_args()
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
